-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.11.4-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.15.0.7171
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for peq
CREATE DATABASE IF NOT EXISTS `peq` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci */;
USE `peq`;

-- Dumping structure for table peq.zone_era
CREATE TABLE IF NOT EXISTS `zone_era` (
  `zone_short` varchar(32) NOT NULL,
  `era` varchar(32) NOT NULL,
  PRIMARY KEY (`zone_short`),
  KEY `idx_era` (`era`),
  KEY `idx_zone_era_zone_short` (`zone_short`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- Dumping data for table peq.zone_era: ~266 rows (approximately)
INSERT INTO `zone_era` (`zone_short`, `era`) VALUES
	('abysmal', 'god'),
	('acrylia', 'luclin'),
	('airplane', 'classic'),
	('akanon', 'classic'),
	('akheva', 'luclin'),
	('anguish', 'oow'),
	('barindu', 'god'),
	('bazaar', 'luclin'),
	('befallen', 'classic'),
	('befallenb', 'classic'),
	('beholder', 'classic'),
	('blackburrow', 'classic'),
	('bloodfields', 'oow'),
	('bothunder', 'pop'),
	('burningwood', 'kunark'),
	('butcher', 'classic'),
	('cabeast', 'kunark'),
	('cabwest', 'kunark'),
	('catacombs', 'oow'),
	('cauldron', 'classic'),
	('causeway', 'oow'),
	('cazicthule', 'loy'),
	('charasis', 'kunark'),
	('chardok', 'kunark'),
	('chardokb', 'loy'),
	('citymist', 'kunark'),
	('cobaltscar', 'velious'),
	('codecay', 'pop'),
	('commonlands', 'classic'),
	('commons', 'classic'),
	('crushbone', 'classic'),
	('crystal', 'velious'),
	('dalnir', 'kunark'),
	('dawnshroud', 'luclin'),
	('dranik', 'oow'),
	('dranikb', 'oow'),
	('draniksscar', 'oow'),
	('dreadlands', 'kunark'),
	('droga', 'loy'),
	('dulak', 'loy'),
	('eastkarana', 'classic'),
	('eastwastes', 'velious'),
	('echo', 'luclin'),
	('ecommons', 'classic'),
	('emeraldjungle', 'kunark'),
	('erudnext', 'classic'),
	('erudnint', 'classic'),
	('erudsxing', 'classic'),
	('everfrost', 'classic'),
	('fearplane', 'classic'),
	('feerrott', 'classic'),
	('feerrott2', 'classic'),
	('felwithea', 'classic'),
	('felwitheb', 'classic'),
	('ferubi', 'god'),
	('fhalls', 'god'),
	('fieldofbone', 'kunark'),
	('firiona', 'kunark'),
	('freeporteast', 'classic'),
	('freeportwest', 'classic'),
	('freporte', 'classic'),
	('freportn', 'classic'),
	('freportw', 'classic'),
	('frontiermtns', 'kunark'),
	('frozenshadow', 'velious'),
	('fungusgrove', 'luclin'),
	('gfaydark', 'classic'),
	('greatdivide', 'velious'),
	('griegsend', 'luclin'),
	('grimling', 'luclin'),
	('grobb', 'classic'),
	('growthplane', 'velious'),
	('guka', 'ldon'),
	('gukb', 'ldon'),
	('gukbottom', 'classic'),
	('gukc', 'ldon'),
	('gukd', 'ldon'),
	('guke', 'ldon'),
	('gukf', 'ldon'),
	('gukg', 'ldon'),
	('gukh', 'ldon'),
	('guktop', 'classic'),
	('gunthak', 'loy'),
	('halas', 'classic'),
	('hateplaneb', 'loy'),
	('hatesfury', 'loy'),
	('highkeep', 'classic'),
	('highpass', 'classic'),
	('highpasshold', 'classic'),
	('hohonora', 'pop'),
	('hohonorb', 'pop'),
	('hole', 'kunark'),
	('hollowshade', 'luclin'),
	('iceclad', 'velious'),
	('icewell', 'velious'),
	('ikkinz', 'god'),
	('inktuta', 'god'),
	('innothule', 'classic'),
	('innothuleb', 'classic'),
	('jaggedpine', 'luclin'),
	('kael', 'velious'),
	('kaesora', 'kunark'),
	('kaladima', 'classic'),
	('kaladimb', 'classic'),
	('karnor', 'kunark'),
	('katta', 'luclin'),
	('kedge', 'classic'),
	('kithicor', 'classic'),
	('kodtaz', 'god'),
	('kurn', 'kunark'),
	('lakeofillomen', 'kunark'),
	('lakerathe', 'classic'),
	('lavastorm', 'classic'),
	('letalis', 'luclin'),
	('lfaydark', 'classic'),
	('maiden', 'luclin'),
	('mira', 'ldon'),
	('mirb', 'ldon'),
	('mirc', 'ldon'),
	('mird', 'ldon'),
	('mire', 'ldon'),
	('mirf', 'ldon'),
	('mirg', 'ldon'),
	('mirh', 'ldon'),
	('miri', 'ldon'),
	('mirj', 'ldon'),
	('mischiefplane', 'god'),
	('mistmoore', 'classic'),
	('misty', 'classic'),
	('mistythicket', 'classic'),
	('mmca', 'ldon'),
	('mmcb', 'ldon'),
	('mmcc', 'ldon'),
	('mmcd', 'ldon'),
	('mmce', 'ldon'),
	('mmcf', 'ldon'),
	('mmcg', 'ldon'),
	('mmch', 'ldon'),
	('mmci', 'ldon'),
	('mmcj', 'ldon'),
	('mseru', 'luclin'),
	('nadox', 'loy'),
	('najena', 'classic'),
	('natimbi', 'god'),
	('necropolis', 'velious'),
	('nedaria', 'ldon'),
	('nektulos', 'classic'),
	('neriaka', 'classic'),
	('neriakb', 'classic'),
	('neriakc', 'classic'),
	('netherbian', 'luclin'),
	('nexus', 'luclin'),
	('nightmareb', 'pop'),
	('nobles', 'oow'),
	('northkarana', 'classic'),
	('northro', 'classic'),
	('nro', 'classic'),
	('nurga', 'loy'),
	('oasis', 'classic'),
	('oceanoftears', 'classic'),
	('oggok', 'classic'),
	('oot', 'classic'),
	('overthere', 'kunark'),
	('paineel', 'classic'),
	('paludal', 'luclin'),
	('paw', 'classic'),
	('permafrost', 'classic'),
	('poair', 'pop'),
	('podisease', 'pop'),
	('poeartha', 'pop'),
	('poearthb', 'pop'),
	('pofire', 'pop'),
	('poinnovation', 'pop'),
	('pojustice', 'pop'),
	('poknowledge', 'pop'),
	('ponightmare', 'pop'),
	('postorms', 'pop'),
	('potactics', 'pop'),
	('potimea', 'pop'),
	('potimeb', 'pop'),
	('potorment', 'pop'),
	('potranquility', 'pop'),
	('povalor', 'pop'),
	('powater', 'pop'),
	('provinggrounds', 'oow'),
	('qcat', 'classic'),
	('qey2hh1', 'classic'),
	('qeynos', 'classic'),
	('qeynos2', 'classic'),
	('qeytoqrg', 'classic'),
	('qinimi', 'god'),
	('qrg', 'classic'),
	('qvic', 'god'),
	('rathemtn', 'classic'),
	('rivervale', 'classic'),
	('riwwi', 'god'),
	('ruinedcity', 'oow'),
	('ruja', 'ldon'),
	('rujb', 'ldon'),
	('rujc', 'ldon'),
	('rujd', 'ldon'),
	('ruje', 'ldon'),
	('rujf', 'ldon'),
	('rujg', 'ldon'),
	('rujh', 'ldon'),
	('ruji', 'ldon'),
	('rujj', 'ldon'),
	('runnyeye', 'classic'),
	('scarlet', 'luclin'),
	('sebilis', 'kunark'),
	('shadeweaver', 'luclin'),
	('shadowhaven', 'luclin'),
	('shadowrest', 'god'),
	('sharvahl', 'luclin'),
	('siren', 'velious'),
	('skyfire', 'kunark'),
	('skyshrine', 'velious'),
	('sleep', 'velious'),
	('sncrematory', 'god'),
	('snlair', 'god'),
	('snplant', 'god'),
	('snpool', 'god'),
	('soldunga', 'classic'),
	('soldungb', 'classic'),
	('soldungc', 'classic'),
	('solrotower', 'pop'),
	('soltemple', 'classic'),
	('southkarana', 'classic'),
	('southro', 'classic'),
	('sro', 'classic'),
	('sseru', 'luclin'),
	('ssratemple', 'luclin'),
	('steamfont', 'classic'),
	('steamfontmts', 'classic'),
	('stonebrunt', 'velious'),
	('swampofnohope', 'kunark'),
	('tacvi', 'god'),
	('takishruins', 'ldon'),
	('takishruinsa', 'ldon'),
	('templeveeshan', 'velious'),
	('tenebrous', 'luclin'),
	('thedeep', 'luclin'),
	('thegrey', 'luclin'),
	('thurgadina', 'velious'),
	('thurgadinb', 'velious'),
	('timorous', 'kunark'),
	('tipt', 'god'),
	('torgiran', 'loy'),
	('tox', 'classic'),
	('toxxulia', 'classic'),
	('trakanon', 'kunark'),
	('twilight', 'luclin'),
	('txevu', 'god'),
	('umbral', 'luclin'),
	('uqua', 'god'),
	('veeshan', 'kunark'),
	('veksar', 'loy'),
	('velketor', 'velious'),
	('vexthal', 'luclin'),
	('vxed', 'god'),
	('wakening', 'velious'),
	('wallofslaughter', 'oow'),
	('warrens', 'velious'),
	('warslikswood', 'kunark'),
	('westwastes', 'velious'),
	('yxtta', 'god');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
